### ISSUE TITLE
Feature Request: Support wildcard for checkName

### ISSUE THREAD

**Issue by dakaneye** [fountainhead/action-wait-for-check#10]
If waiting for a series of checks run against a matrix (i.e. tests), you have to add a check step for each individual job in that matrix.

Example workflow snippet:
```yaml
      - name: Check acceptance test results (helm)
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: acceptance-helm-1-13-12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Acceptance-Helm (v1.13.12)"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Check acceptance test results (helm)
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: acceptance-helm-1-18-0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Acceptance-Helm (v1.18.0)"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
```
