### ISSUE TITLE
checkName documentation 

### ISSUE THREAD

**Issue by AzySir** [fountainhead/action-wait-for-check#13]
Could someone please elaborate on the below documentation. What is this actually referring to what name is it checking? Branch Name, Repo Name? 

**checkName**

Required

The name of the GitHub check to wait for. For example, `build` or `deploy`.

**Comment by wms** [comment]
`checkName` refers to the name of a [GitHub Check](https://docs.github.com/en/rest/reference/checks).

By default, this would be a Check on the same repo and branch that the check is running against. However, this can be customized via the `ref` and `repo` options.

**Comment by AzySir** [comment]
But there's no default right - because it's a required value...

**Comment by wms** [comment]
You are correct that `checkName` is required - what I meant is that `ref` and `repo` are optional, and by default they refer to the current repo and branch.

**Comment by rcdailey** [comment]
I'm sorry, but linking to an API page is not a sufficient answer to the OP's question. This still doesn't make any sense to me. That API page doesn't seem to explain *what checks are*. In my mind, I need to just see if a build for a specific SHA1 is completed or not. How do I go about doing that? Nothing I put in for `checkName` works.

**Comment by wms** [comment]
For checking if a specific build for a specific commit has completed you need to combine `checkName` with `ref` options:

```
checkName: name-of-build
ref: your-specific-sha
```

**Comment by rcdailey** [comment]
I'm still not able to get this to work. Here is what happens:

> No completed checks named Build, waiting for 10 seconds...
> No completed checks after 600 seconds, exiting with conclusion 'timed_out'

You can see my YAML [here](https://github.com/rcdailey/trash-updater-test/blob/master/.github/workflows/release.yml). The wait-specific part is here:

```yml
name: Release

on:
  push:
    tags:
      - 'v*.*'

defaults:
  run:
    working-directory: src

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.PAT }}
          checkName: Build
          ref: ${{ github.sha }}

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PAT }}
          workflow: build.yml
          commit: ${{ github.sha }}
```

It is supposed to be waiting for the [build workflow here](https://github.com/rcdailey/trash-updater-test/blob/master/.github/workflows/build.yml), this job:

```yml
name: Build

...

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: ...

  build:
    name: Build
    needs: test
    strategy:
      fail-fast: true
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: ...
```
