### ISSUE TITLE
Can't retrieve result on workflow dispatch event

### ISSUE THREAD

**Issue by sunRock98** [fountainhead/action-wait-for-check#43]
I have workflow with two jobs, second job at some step waits for first job to finish. Everything works as expected if
```
on:
 pull_request:
    types: [opened, synchronize, reopened]
 workflow_dispatch:
```
but if I delete this pull_request trigger and leave only 
```
on:
  workflow_dispatch:
```
wait step could not get info and prints 
`Retrieved 0 check runs named ...`

Any suggestions?
